name: 'json-diff-file-action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  first:
    required: true
    description: 'input description here'
  second:
    required: true
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
